### ISSUE TITLE
ImportError: Failure to connect with bridging executable - Configurable Timeouts

### ISSUE THREAD

**Issue by jloehel** [burgerbecky/wslwinreg#2]
Hi Rebecca,

thanks for the awesome pymodule. :100: It works fine but I have some small issues with the timeouts. In example here:

https://github.com/burgerbecky/wslwinreg/blob/22ebf8603ff3c30f911755fba257c2882f260a6d/wslwinreg/wslapi.py#L177

Do you think it would be possible to make them configurable. Sometime the application runs into `ImportError: Failure to connect with bridging executable`. If I adjust the timeout from 3.0 to 10.0 it works fine. Maybe a retry mechanism would also help.

**Comment by burgerbecky** [comment]
I'll add this shortly

**Comment by burgerbecky** [comment]
Update to 1.0.8 with pip install -U wslwinreg. I've updated the timeout to 10 seconds
